# This is a sample build configuration for other languages.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: pritunl/archlinux 

pipelines:
  default:
    - step:
        script:
          - uname -a
          - echo $BITBUCKET_COMMIT $BITBUCKET_BRANCH $BITBUCKET_REPO_SLUG $BITBUCKET_REPO_OWNER
          - pwd
          - echo '[multilib]' >> /etc/pacman.conf
          - echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
          - echo 'Server = http://mirror.lty.me/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
          - pacman -Sy tree wine-staging xorg-server-xvfb mercurial --noconfirm --noprogressbar --needed
          - hg log
          - hg log -l 1 --template "{rev}\n"
          - hg log -l 1 --template "{desc}\n" # | grep -i '+workshop'
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/mbw_workshop_uploader_glsl_pdf.exe
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/steam_api.dll
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/Steam.exe
          - Xvfb :1 -screen 0 800x600x16 &
          - export DISPLAY=:1
          - tree .
          - WINEDLLOVERRIDES="mscoree,mshtml=" wineboot -u
          - WINEDEBUG=-all wine steam -silent -debug_steamapi -forceservice -no-browser -no-cef-sandbox -opengl -login swyter "$STEAM_PASSWORD" &
          - sleep 135
          - chmod +x _wb/_setup_symlinks.sh
          - #_wb/_setup_symlinks.sh
          - mv _wb 'Native with spaces'
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/native_test.ini
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/swconquest.png
          - echo 48700 > steam_appid.txt
          - yes NO | env WINEDEBUG=-all wine mbw_workshop_uploader_glsl_pdf.exe update -mod native_test.ini -id 746900895 -icon swconquest.png -changes "Test with actual stuff. ${hg log -l 1 --template '{desc}\n'}"