# This is a sample build configuration for other languages.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
pipelines:
  default:
    - step:
        script:
          - #curl "$BUILDBOT_KICKOFF_URL"
          - uname -a
          - echo $BITBUCKET_COMMIT $BITBUCKET_BRANCH $BITBUCKET_REPO_SLUG $BITBUCKET_REPO_OWNER
          - pwd
          - hg log -r "$BITBUCKET_COMMIT" --template "{desc}\n" # | grep -I '!workshop' # don't deploy if this string is not in the commit log!
          - HG_REV="$(hg log -l 1 --template     "{rev}")"
          - HG_LOG="$(hg log -l 1 --template "\n\n{desc}\n")" # | grep -i '+workshop'
          - WORKSHOP_DESC="Submitted hg revision ${HG_REV}; ${HG_LOG}"
          - cd ..
          - sudo add-apt-repository universe -yy
          - sudo dpkg --add-architecture i386 -yy
          - sudo add-apt-repository ppa:wine/wine-builds -yy
          - sudo apt-get update -yy
          - sudo apt-get install --install-recommends wine-staging winehq-staging mercurial xvfb tree winetricks flip curl unzip lsof -yy --force-yes
          - Xvfb :1 -screen 0 800x600x16 &
          - export DISPLAY=:1
          - #tree .
          - mkdir steam && cd steam
          - curl -LOJs 'https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/Steam.exe'
          - curl -LOJs "$STEAM_SS"
          - export WINEDLLOVERRIDES="mscoree,mshtml="
          - export WINEDEBUG=-all
          - wineboot -u
          - winetricks sound=disabled
          - wine steam -silent -forceservice -no-browser -no-cef-sandbox -opengl -login swyter "$STEAM_PASSWORD" &
          - ((t = 290)); while ((t > 0)); do grep 'RecvMsgClientLogOnResponse()' --no-messages logs/connection_log.txt | grep 'OK' && break; grep --no-messages 'RecvMsgClientLogOnResponse()' logs/connection_log.txt | grep --no-messages 'Account Logon Denied' && exit 1; ((t == 1)) && exit 1; sleep 1 && echo ' >>' $[ t-- ]; done
          - # give it some seconds to settle down, slowpoke!
          - sleep 20
          - echo 'Logged in correctly in Steam!'
          - cd ../build
          - cp Font/FONT_DATA.XML _wb/Data/font_data.xml
          - cp Font/FONT_SWC.dds  _wb/Textures/font.dds
          - curl -LOJ 'https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/vanilla_glsl_opt.zip'
          - unzip vanilla_glsl_opt.zip -d _wb
          - rm -f vanilla_glsl_opt.zip
          - cp -rf ./_wb/* ./
          - rm -rf _wb
          - mv GLShaders/*.glsl  GLShadersOptimized/
          - mv Languages languages
          - chmod +x _strip_unused.sh
          - ./_strip_unused.sh
          - rm -rf .hg
          - cd ..
          - ls -lash .
          - #lsof +D ./build
          - cp -r build 'Star Wars Conquest'
          - curl -LOJ https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/mbw_workshop_uploader_glsl.exe
          - curl -LOJ https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/steam_api.dll
          - curl -LOJ https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/swconquest.ini
          - curl -LOJ https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/swconquest.png
          - echo 48700 > steam_appid.txt
          - yes NO | env WINEDEBUG=-all wine mbw_workshop_uploader_glsl.exe update -mod swconquest.ini -id 742671195 -icon swconquest.png -changes "$WORKSHOP_DESC"
          - sleep 10
          - killall -I steam.exe
