# This is a sample build configuration for other languages.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: pritunl/archlinux

pipelines:
  default:
    - step:
        script:
          - uname -a
          - echo $BITBUCKET_COMMIT $BITBUCKET_BRANCH $BITBUCKET_REPO_SLUG $BITBUCKET_REPO_OWNER
          - pwd
          - echo '[multilib]' >> /etc/pacman.conf
          - echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
          - echo 'Server = http://mirror.lty.me/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
          - pacman -Sy tree wine-staging xorg-server-xvfb mercurial unzip --noconfirm --noprogressbar --needed
          - HG_REV="$(hg log -l 1 --template     "{rev}")"
          - HG_LOG="$(hg log -l 1 --template "\n\n{desc}\n")" # | grep -i '+workshop'
          - WORKSHOP_DESC="Submitted hg revision ${HG_REV}; ${HG_LOG}"
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/mbw_workshop_uploader_glsl.exe
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/steam_api.dll
          - Xvfb :1 -screen 0 800x600x16 &
          - export DISPLAY=:1
          - tree .
          - mkdir steam && cd steam
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/Steam.exe
          - WINEDLLOVERRIDES="mscoree,mshtml=" wineboot -u
          - WINEDEBUG=-all wine steam -silent -forceservice -no-browser -no-cef-sandbox -opengl -login swyter "$STEAM_PASSWORD" &
          - cd ..
          - sleep 135
          - chmod +x _wb/_setup_symlinks.sh
          - chmod +x _wb/_strip_unused.sh
          - curl https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/vanilla_glsl_opt.zip -L -O
          - unzip vanilla_glsl_opt.zip -d _wb
          - cd _wb
          - mkdir Textures
          - cp -r ../Languages   languages
          - mv Resource _wb_res
          - cp -r ../Resource    Resource
          - mv _wb_res/*         Resource/
          - rm _wb_res
          - cp -r ../Textures/*  Textures/
          - cp -r ../SceneObj    .
          - cp -r ../Music       .
          - cp -r ../Sounds      .
          - mv GLShaders/*.glsl  GLShadersOptimized/
          - ./_setup_symlinks.sh
          - ./_strip_unused.sh
          - tree .
          - cd ..
          - mv _wb 'Native with spaces'
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/native_test.ini
          - curl -L -O https://github.com/tldmod/tldmod/releases/download/TLD3.3REL/swconquest.png
          - echo 48700 > steam_appid.txt
          - yes NO | env WINEDEBUG=-all wine mbw_workshop_uploader_glsl.exe update -mod native_test.ini -id 746900895 -icon swconquest.png -changes "$WORKSHOP_DESC"
          - sleep 10
          - killall -I steam.exe
